---
title: 'Clase 1: Entrega 4'
author: "Santiago Olszevicki"
date: "2025-05-19"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Definición de funciones


```{r}
 
 est1_unif<-function(datos){
   2*mean(datos)
 }
 est2_unif<-function(datos){
   max(datos)
 }

```


# Item a y b
```{r}
histograma_est_unif <- function(theta, n, Nrep, seed, estim = est1_unif, plot = "hist"){
  est_s <- c()
  set.seed(seed)
  for (rep in 1:Nrep){
    data <- runif(n = n, min = 0, max = theta)
    est_s <- c(est_s, estim(data))
  }
  if(plot == "hist"){
    hist(est_s, xlim = c(theta-3, theta+3), main = paste0("n=",n))
  }
    else{(plot(density(est_s)))}
  
}
```

# Item c
Nota: para cada n, se muestra primero el histograma para el estimador de momentos (izq), seguido del de máxima verosimilitud (der).
```{r, fig.width=4, fig.height=3}
ns <- c(5,30,50,100,1000)
for (n in ns){
  histograma_est_unif(theta = 3, n = n, Nrep = 1000, seed = 11081, estim = est1_unif)
   histograma_est_unif(theta = 3, n = n, Nrep = 1000, seed = 11081, estim = est2_unif)
}
```

# Item d: ECM empirico
```{r}
ecm_empirico_est_unif <- function(theta, n, Nrep, seed, estim = est1_unif){
  est_s <- c()
  set.seed(seed)
  for (rep in 1:Nrep){
    data <- runif(n = n, min = 0, max = theta)
    est_s <- c(est_s, estim(data))
  }
  1/Nrep * sum((est_s - theta)**2)
}


ns <- c(5, 30, 50, 100, 1000)
ecm1 <- c()
ecm2 <- c()

for (n in ns) {
  ecm1_val <- ecm_empirico_est_unif(theta = 3, n = n, Nrep = 1000, seed = 11081, estim = est1_unif)
  ecm2_val <- ecm_empirico_est_unif(theta = 3, n = n, Nrep = 1000, seed = 11081, estim = est2_unif)
  ecm1 <- c(ecm1, ecm1_val)
  ecm2 <- c(ecm2, ecm2_val)
}

tabla_ecm <- data.frame(
  n = ns,
  ECM_est1 = round(ecm1, 4),
  ECM_est2 = round(ecm2, 4)
)

knitr::kable(tabla_ecm, caption = "ECM empíricos")

```
Item e: ECM teórico.

```{r} 

ns <- c(5, 30, 50, 100, 1000)
theta <- 3
ecm1_teo <- c()
ecm2_teo <- c()

for (n in ns) {
  ecm1_val <- theta**2 / (3*n)
  ecm2_val <- 2*theta**2 / ((n+1)*(n+2))
  ecm1_teo <- c(ecm1_teo, ecm1_val)
  ecm2_teo <- c(ecm2_teo, ecm2_val)
}

tabla_ecm_teo <- data.frame(
  n = ns,
  ECM_est1 = round(ecm1_teo, 4),
  ECM_est2 = round(ecm2_teo, 4)
)
knitr::kable(tabla_ecm_teo, caption = "ECM teóricos")


```