---
title: "Estimadores de momentos y ML: Poisson"
author: "Olszevicki Santiago"
output: pdf_document
---
Sean \( X_1, X_2, \ldots, X_n \) m.a. i.i.d. tal que \( X_i \sim \text{Poisson}(\theta) \), con \( \theta > 0 \) desconocido.

La función de probabilidad puntual es:

\[
P(X = x) = \frac{e^{-\theta} \theta^x}{x!}, \quad x = 0, 1, 2, \ldots
\]
Además, sabemos que $\mathbb{E}[X] = \theta$

\section*{Estimador de momentos}

El primer momento muestral es: $\bar{X} = \frac{1}{n} \sum_{i=1}^n X_i = \hat{\theta}_{momentos}$




Por lo tanto, el estimador de momentos para \( \theta \) es simplemente la media muestral.

### Consistencia
Por la LGN, y según está planteado el problema, sabemos que el promedio muestral de variables i.i.d converge en probabilidad a la esperanza de una de ellas. 
Entonces, $\bar{X} \xrightarrow{p} \theta \quad \text{cuando } n \to \infty$
Por lo tanto, \( \hat{\theta}_{momentos} \) es un estimador \textbf{consistente} de \( \theta \).

### Sesgo

 Como $\mathbb{E}[\bar{X}] = \theta$ (por propiedades de la esperanza), el sesgo es cero: $\mathbb{B}(\hat{\theta}_{momentos}) = \mathbb{E}[\hat{\theta}_{momentos}] - \theta = 0$. Por lo tanto, $\hat{\theta}_{momentos}$ es insesgado.
 
### Distribución asintótica


Con $\hat{\theta}_{momentos} = \bar{X}$, con $X_i$ i.i.d. con media $\theta$ y varianza $\mathrm{Var}(X_i) = \theta$. Por el Teorema Central del Límite, el promedio muestral estandarizado converge en distribución a una normal estándar. Por lo tanto, este estimador es asintóticamente normal

\[
\frac{\sqrt{n}(\hat{\theta}_{momentos} - \theta)}{\sqrt{\theta}} \xrightarrow{\mathrm{D}}\mathcal{N}(0,1).
\]




\section*{Estimador de máxima verosimilitud}

La función de verosimilitud de la muestra es:

\[
L(\theta; X_1, \ldots, X_n) = \prod_{i=1}^n \frac{\theta^{X_i} e^{-\theta} }{X_i!}
= \theta^{\sum X_i} e^{-n\theta} \prod_{i=1}^n \frac{1}{X_i!}
\]

Tomo logaritmo:

\[
\ell(\theta) = \ln L(\theta) =  \left( \sum_{i=1}^n X_i \right) \ln \theta -n\theta  - \sum_{i=1}^n \ln(X_i!)
\]

Derivo respecto de \( \theta \) e igualo a cero:


\[
 \frac{\sum x_i}{\theta} -n= 0
\quad \Rightarrow \quad
\hat{\theta}_{MV}  = \frac{1}{n} \sum x_i = \bar{X}
\]

Por lo tanto, el estimador de máxima verosimilitud y el de momentos son el mismo: la media muestral. 
Por ello, sus propiedades (consistencia, insesgadez y distrubición asintótica) se mantienen.

\[
\hat{\theta}_{MV} = \bar{X}
\]


